# -*- Makefile -*- --------------------------------------------------------
# @@COPYRIGHT@@
#*-------------------------------------------------------------------------
# @file
# @brief

CML_ROOT=../
include makeconf

VEC_TEST_SRC	= vector_et1.cpp
VEC_TESTS	= vector_et1$(exe)

MAT_TEST_SRC	= matrix_et1.cpp
MAT_TESTS	= matrix_et1$(exe)

ALL_SRC		= $(VEC_TEST_SRC) \
		  $(MAT_TEST_SRC)

ALL_TESTS	= $(VEC_TESTS) \
		  $(MAT_TESTS)

ALL=	$(ALL_TESTS)

include makepost

# --------------------------------------------------------------------------
# vim:ft=make
