# SPDX short identifier: BSL-1.0

name: msvc-latest.yml
on:
  push:
    paths:
      - '.github/**'
      - 'cmake/**'
      - 'cml/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'CML.cmake'
      - 'vcpkg.json'

jobs:
  msvc-latest:
    name: MSVC Latest
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.29.0"
      - uses: lukka/run-vcpkg@v11
      - uses: lukka/run-cmake@v10
        with:
          configurePreset: "cml-ci-ninja-msvc-mt-s"
          buildPreset: "cml-ci-ninja-msvc-mt-s-release"
          testPreset: "cml-ci-ninja-msvc-mt-s-release-test"