
name: msvc
on:
  push:
    paths:
      - '.github/**'
      - 'cmake/**'
      - 'cml/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'CML.cmake'
      - 'vcpkg.json'

jobs:
  msvc-17:
    strategy:
      fail-fast: false
      matrix:
        include:
        - ver: 14.40
          vsver: 17.10
        - ver: 14.42
          vsver: 17.12
        - ver: 14.44
          vsver: 17.14
    env:
      # Consumed by .msvc-17 in cmake/presets/msvc.json:
      MSVC_TOOLSET_VERSION: ${{ matrix.ver }}
    name: "(msvc-17-${{ matrix.ver }})"
    runs-on: windows-2022
    steps:
        # Set the number of CMake build and test jobs
      - shell: pwsh
        run: |
          $nproc = (Get-WmiObject -Class Win32_ComputerSystem -Property NumberOfProcessors).NumberOfProcessors
          $ncore = (Get-WmiObject -Class Win32_Processor -Property NumberOfCores).NumberOfCores
          Write-Host $nproc
          Write-Host $ncore

          $ncore = (Get-WmiObject -Class Win32_Processor -Property NumberOfCores `
                   | Measure-Object -Property NumberOfCores -Sum).Sum
          "CMAKE_BUILD_PARALLEL_LEVEL=$($ncore)" | Out-File -Append $env:GITHUB_ENV
          "CTEST_PARALLEL_LEVEL=$($ncore)" | Out-File -Append $env:GITHUB_ENV
      - name: Install MSVC ${{ matrix.ver }}.${{ matrix.vsver }}
        shell: pwsh
        run: |
          $vspath = 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'
          Test-Path -Path $vspath | Should -Be $true

          $vsinstaller = 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe'
          Test-Path -Path $vsinstaller | Should -Be $true

          Start-Process -NoNewWindow -Wait -FilePath $vsinstaller -ArgumentList `
            'modify', '--installPath', "`"$vspath`"", '--quiet', '--norestart', '--nocache', '--noUpdateInstaller', `
            '--add', 'Microsoft.VisualStudio.Component.VC.${{ matrix.ver }}.${{ matrix.vsver }}.x86.x64'
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.31.0"
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      - name: Build and test
        shell: pwsh
        run: |
           Write-Host "Building for MSVC $($env:MSVC_TOOLSET_VERSION) with VCPKG_ROOT @ $($env:VCPKG_ROOT)"
           cmake --workflow --preset=msvc-17-mt-s-vcpkg-release-test