# SPDX short identifier: BSL-1.0

name: ninja-msvc17
on: push

jobs:
  job:
    name: VS 2022 update test
    runs-on: windows-2022
    steps:
      - name: Run vs_installer.exe
        shell: pwsh
        run: |
          $vsinstaller = 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe'
          Test-Path -Path $vsinstaller | Should -Be $true

          $modify = Start-Process -Wait -PassThru -FilePath $vsinstaller `
            -ArgumentList 'modify', '--add', 'Microsoft.VisualStudio.Component.VC.14.40.17.10.x86.x64', '--quiet', '--wait'
          Write-Host $modify.ExitCode

          $vsbin = 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64'
          $clexe = Join-Path $vsbin 'cl.exe'
          Test-Path -Path $clexe | Should -Be $true
          & $clexe /?