# SPDX short identifier: BSL-1.0

name: ninja-msvc17
on: push

jobs:
  job:
    name: MSVC 17.10, CMake 3.27
    runs-on: windows-2022
    steps:
      - name: Install MSVC 17.10
        shell: pwsh
        run: |
          $vspath = 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise'
          Test-Path -Path $vspath | Should -Be $true

          $vsinstaller = 'C:\Program Files (x86)\Microsoft Visual Studio\Installer\vs_installer.exe'
          Test-Path -Path $vsinstaller | Should -Be $true

          Start-Process -NoNewWindow -Wait -FilePath $vsinstaller -ArgumentList `
            'modify', '--installPath', "`"$vspath`"", '--quiet', '--norestart', '--nocache', '--noUpdateInstaller', `
            '--add', 'Microsoft.VisualStudio.Component.VC.14.40.17.10.x86.x64'

      - name: Pull cmake 3.27
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.27.0"
          useCloudCache: true

      - name: Checkout CML
        uses: actions/checkout@v4

      - name: Build and test with MSVC 17.10
        uses: lukka/run-cmake@v10
        with:
          configurePreset: "cml-ci-msvc17-mt-s",
          configurePresetAdditionalArgs: "['-T version=14.40']"
          buildPreset: "cml-ci-msvc17-mt-s-release",
          testPreset: "cml-ci-msvc17-mt-s-release-test"