
name: windows-msbuild-msvc
on:
  pull_request:
    paths:
      - '.github/**'
      - 'cmake/**'
      - 'cml/**'
      - 'tests/**'
      - 'CMakeLists.txt'
      - 'CMakePresets.json'
      - 'CML.cmake'
      - 'vcpkg.json'

jobs:
  build-and-test:
    permissions:
      checks: write
    strategy:
      fail-fast: false
      matrix:
        include:
        - ver: "14.40"
          vsver: "17.10"
          cmake: "3.31.0"
          preset: "windows-msbuild-msvc-17-mt-s-vcpkg"
        - ver: "14.42"
          vsver: "17.12"
          cmake: "3.31.0"
          preset: "windows-msbuild-msvc-17-mt-s-vcpkg"
        - ver: "14.44"
          vsver: "17.14"
          cmake: "3.31.0"
          preset: "windows-msbuild-msvc-17-mt-s-vcpkg"
        - ver: "14.50"
          vsver: "18.0"
          cmake: "4.4.0"
          preset: "windows-msbuild-msvc-18-mt-s-vcpkg"
        - ver: "14.51"
          vsver: ""
          cmake: "4.4.0"
          preset: "windows-msbuild-msvc-18-mt-s-vcpkg"
    env:
      MSVC_TOOLSET_VERSION: ${{ matrix.ver }}
    name: "(windows-msbuild-msvc-mt-s-vcpkg-${{ matrix.ver }})"
    runs-on: windows-2025
    steps:
      - name: Set CMake and CTest concurrency
        shell: pwsh
        run: |
          $ncore = (Get-WmiObject -Class Win32_Processor -Property NumberOfCores `
                   | Measure-Object -Property NumberOfCores -Sum).Sum
          "CMAKE_BUILD_PARALLEL_LEVEL=$($ncore)" | Out-File -Append $env:GITHUB_ENV
          "CTEST_PARALLEL_LEVEL=$($ncore)" | Out-File -Append $env:GITHUB_ENV
      - name: Install MSVC ${{ matrix.ver }}.${{ matrix.vsver }}
        shell: pwsh
        run: |
          Install-Module -Name VSSetup -Force

          # Special case for the 14.51 workload in VS 18.6+:
          $ver = "${{ matrix.ver }}"
          $vsver = "${{ matrix.vsver }}"
          if([String]::IsNullOrEmpty($vsver)) {
            $workload = "Microsoft.VisualStudio.Component.VC.$($ver).x86.x64"
          } else {
            $workload = "Microsoft.VisualStudio.Component.VC.$($ver).$($vsver).x86.x64"
          }

          # Find the installed VS version:
          $vs = Get-VSSetupInstance | Sort-Object -Property InstallationVersion -Descending | Select-Object -First 1

          # Determine if the required workload is installed:
          $candidates = $vs.Packages | Where-Object Id -eq $workload
          if($candidates.Count -eq 1) {
            Write-Host "Workload $($workload) is already installed"
          } else {
            $vsinstaller = 'C:/Program Files (x86)/Microsoft Visual Studio/Installer/vs_installer.exe'
            if(!(Test-Path -Path $vsinstaller)) {
              Write-Error "Could not locate the Visual Studio installer"
              Exit 1;
            }

            Write-Host "... installing $($workload) for $($vspath)"
            Start-Process -NoNewWindow -Wait -FilePath $vsinstaller -ArgumentList `
              'modify', '--installPath', "`"$vspath`"", '--quiet', '--norestart', '--nocache', '--noUpdateInstaller', `
              '--add', "$($workload)"

            $vs = Get-VSSetupInstance | Sort-Object -Property InstallationVersion -Descending | Select-Object -First 1
            $candidates = $vs.Packages | Where-Object Id -eq $workload
            if($candidates.Count -eq 0) {
              Write-Error "Installation of $($workload) for $($vspath) failed"
              Exit 1;
            }
            Write-Host "Successfully installed workload $($workload)"
          }
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~${{matrix.cmake}}"
      - uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      - name: Build and test
        shell: pwsh
        run: |
           $preset = "${{matrix.preset}}"
           Write-Host "Executing workflow $($preset) for MSVC $($env:MSVC_TOOLSET_VERSION) with VCPKG_ROOT @ $($env:VCPKG_ROOT)"
           cmake --workflow --preset=$preset
      - name: Generate JUnit test results
        uses: ctrf-io/github-test-reporter@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          report-path: "ctest.xml"
          status-check-name: "${{matrix.preset}}-${{ matrix.ver }} CTest Report"
          status-check: true
          annotate: true
          summary: true
          use-suite-name: true
          file-report: true
          failed-report: true
          upload-artifact: false
          integrations-config: |
            {
              "junit-to-ctrf": {
                "enabled": true,
                "action": "convert",
                "options": {
                  "output": "ctrf.json",
                  "toolname": "junit-to-ctrf",
                  "useSuiteName": false,
                  "env": {
                    "appName": "cml"
                  }
                }
              }
            }
        if: ${{ always() }}